name: Validate CSV data

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      csv-path:
        required: true
        type: string
      schema-path:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      csv-path:
        description: 'Path to CSV file'
        required: true
        type: string
      schema-path:
        description: 'Path to schema file'
        required: true
        type: string

jobs:
  validate_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clone sparks-tools
        run: |
          git clone https://github.com/statsvine/sparks-tools.git tools
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt || true

      - name: Run CSV validation on csv file
        run: |
          python3 tools/crosswalk/validate_csv.py ${{ inputs.csv-path }} --schema ${{ inputs.schema-path }} --fail-fast